react_05
dpr0/react_js pull request #5
Opened 2017-11-19 18:30 UTC by dpr0

2017-11-25 10:54 UTC, blackleadsu requested changes

2017-11-25 10:54 UTC, blackleaden commented on .gitignore
>  yarn-debug.log*
Также в гитигнор стоит добавить dist

2017-11-25 10:54 UTC, blackleaden commented on src/components/containers/PostContainer.js
> +    request.get(
Если ты это запускал, то наверное заметил, что request ниоткуда не импортируется и не определен.

2017-11-25 10:54 UTC, blackleaden commented on src/components/containers/PostContainer.js
> +      'http://localhost:3001',
Стоит сделать запрос к отдельному посту, а не вытягивать всё содержимое для отображения единственной записи. Плюс, зачастую на внутренней странице выводится гораздо больше данных записи, чем в списке.

2017-11-25 10:54 UTC, blackleaden commented on src/components/containers/PostContainer.js
> +      (err, res) => this.setState({ post: res.body.id })
Даже если это не запускать, видно логическую ошибку:  у списка постов нет свойства id, а даже если и есть там не может динамически лежать нужный нам пост.

2017-11-25 10:54 UTC, blackleaden commented on src/components/containers/PostContainer.js
> +    clonedPost.like == undefined ? (clonedPost.like = 1) : (clonedPost.like += 1);
можно просто `clonedPost.like ? (clonedPost.like = 1) : (clonedPost.like += 1)`

2017-11-25 10:54 UTC, blackleaden commented on src/components/containers/CameraContainer.js
> +class CameraContainer extends React.Component {
Всё, что не по заданию -- в отдельной ветке.

2017-11-25 10:54 UTC, blackleaden commented on src/components/containers/ForumPageContainer.js
> +class ForumPageContainer extends React.Component {
Хорошо, что делаешь что-то своё, но для удобства, пожалуйста, выдели в отдельную ветку то, что не связано непосредственно с заданием.

2017-11-25 10:54 UTC, blackleaden commented on src/components/containers/PostContainer.js
> +    this.setState({ post: clonedPost });
Очевидно, лайки уже не работают как нужно. При переходе со страницы на страницу счетчик лайков сбрасывается. Круто будет, если ты сделаешь лайк через API -- чтобы счетчик сохранялся. Либо можно сделать через redux -- в следующем задании.

2017-11-25 10:54 UTC, blackleaden commented on src/components/layouts/MainLayout.js
> +import { postPath } from '../../helpers/routes';
рекомендую настроить абсолютные пути в конфиге вебпака от src

2017-11-25 10:54 UTC, blackleaden commented on src/components/ui/CameraList.js
> +import _         from 'lodash';
можно так: `import { map } from 'lodash';`

2017-11-25 10:54 UTC, blackleaden commented on src/components/layouts/MainLayout.js
> +  <Button onClick={ () => history.goBack() }>Назад</Button>
Впервые заходим на главную. Видим кнопку "Назад". Нажимаем -- попадаем на пустую страницу. 
Туда же попадаем если заходим по прямой ссылке на внутреннюю страницу записи. 
Очевидно, это так на продакшн-проекте не должно работать. 
Лучше убрать эту кнопку, тем более что по заданию она не требуется.

2017-11-26 05:40 UTC, dpr0 commented on src/components/containers/PostContainer.js
> +    clonedPost.like == undefined ? (clonedPost.like = 1) : (clonedPost.like += 1);
тогда наверное наоборот -
clonedPost.like ? (clonedPost.like += 1) : (clonedPost.like = 1)

2017-11-28 05:46 UTC, blackleaden commented on src/components/containers/PostContainer.js
> +    clonedPost.like == undefined ? (clonedPost.like = 1) : (clonedPost.like += 1);
да)

2017-11-28 06:15 UTC, blackleadsu approved these changes
Зря убрал ссылку на внуреннюю страницу поста. В остальном всё исправлено. Пруф.

2017-11-28 06:15 UTC, blackleaden commented on src/components/ui/BlogItem.js
> -          <Link to={postPath(id)}>{title}</Link>
Зря убрал ссылку.

2017-11-28 07:33 UTC, dpr0 commented on src/components/ui/BlogItem.js
> -          <Link to={postPath(id)}>{title}</Link>
Нечаянно убрал, потом заметил, когда тестил и хотел перейти с индекса в пост))

2017-11-30 05:56 UTC, merged